// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pavmfuvtflfsdzrlzrcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhdm1mdXZ0Zmxmc2R6cmx6cmNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDk2OTcsImV4cCI6MjA2NDAyNTY5N30.8lmLcFt3Q_yJWDcnOfGIH410VecITlCig7cwEyHzlq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);